pipeline {
    agent any

  stages {
    stage('Build') {
      steps {
        script {
          sh 'echo "Building Stage"'
        }
      }
    }
    stage('Package') {
      steps {
        script {
          sh 'echo "Package Stage"'
        }
      }
    }
    }
}
    
